version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mingle
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
#  BeforeInstall:
#    - location: scripts/before_install.sh
#      timeout: 300
#      runas: ubuntu
#  Install:
#    - location: scripts/install.sh
#      timeout: 300
#      runas: ubuntu
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
#  ApplicationStop:
#    - location: /scripts/stop.sh
#      timeout: 300
#      runas: ubuntu
#  ValidateService:
#    - location: scripts/validate_service.sh
#      timeout: 300
#      runas: ubuntu