spring:
#  mvc:
#    cors:
#      allowed-origins: http://mingle-front-bucket.s3-website.ap-northeast-2.amazonaws.com
#      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#      allowed-headers: "*"
#      allow-credentials: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mingledb
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/mingle_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 123456789
#
#  sql:
#    init:
#      mode: always

  jpa:  # https://joyerim.tistory.com/6#%E2%96%AA%C2%A0JPA-1
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop



    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    key: ${JWT_SECRET_KEY}
    live:
      atk: 300000
      rtk: 3000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000

    auth-code-expiration-millis: 300000

  batch:
    job:
      enabled: false
      name: importFrequentCustomerJob, reservationStatisticsJob, birthdayReminderJob, purchaseItemJob
    jdbc:
      initialize-schema: always


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

server:
  port: 8080
